### ISSUE TITLE
Create github pages

### ISSUE THREAD

**Issue by billdenney** [sfirke/tabyl#2]
@sfirke, can you please run `usethis::use_pkgdown_github_pages()` after checking out this repo?

**Comment by sfirke** [comment]
Yes, then I'll send the resulting change back to the repo?

**Comment by billdenney** [comment]
Yes, please. (You may need to do another pull to get the changes I've made in the past few hours.)

**Comment by sfirke** [comment]
Voila! https://sfirke.github.io/tabyl/
